comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Module"
imports_layout = "Horizontal"
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
group_imports = "StdExternalCrate"